Create HistoryView
iOS-vk-education/2023_1_SwipeMovie pull request #16
Opened 2023-11-20 17:57 UTC by Apollonoff

2023-11-24 19:18 UTC, KristinaKulabuhova requested changes

2023-11-25 11:09 UTC, Apollonoff commented on SwipeMovie/SwipeMovie/Modules/History/HistoryViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "MovieCell", for: indexPath) as!  MovieCustomCell
Я сначала написал через guard и fatal error, но думаю, это не самая лучшая практика. Как лучше всего обработать? Можно через UIAlertController

2023-11-25 11:38 UTC, Apollonoff commented on SwipeMovie/SwipeMovie/Modules/TabBar/TabBarController.swift
>          let tabBarController = UITabBarController()
<img width="455" alt="Снимок экрана 2023-11-25 в 14 35 53" src="https://github.com/iOS-vk-education/2023_1_SwipeMovie/assets/87206546/7428df9f-571e-47d5-9696-bf18e780cfe8">
При скролле фон таббара и навбара менялся. Нашел такое решение проблемы, не знаю как иначе. Может есть другое решение?

2023-12-14 10:03 UTC, KristinaKulabuhova approved these changes

2023-12-14 10:03 UTC, merged